trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  # docker image namespace
  imageNamespace: my-docker-id
  # docker image name
  imageName: my-image-name


steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    docker build -t test/img .
    curl -sSL https://mondoo.io/download.sh | bash 
    echo ${MONDOO_CLIENT_ACCOUNT} | base64 -d > mondoo.json
    ./mondoo scan -t docker://test/img --config mondoo.json 
