name: mondoo-scan

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Scan with Mondoo
        uses: mondoohq/actions@main
        with:
          service_account_credentials: ${{ secrets.MONDOO_CLIENT_ACCT }}
          scan_type: docker_image
          docker_image_name: ubuntu:22.04
